# Need sudo to use the puppet installs
sudo: required

# C++ code on trusty
language: cpp
os: linux
dist: trusty

# Most modern travis image
group: edge

# ccache makes things waaaaay faster
cache:
  ccache: true
  directories:
    # This cache is used for deb files so we don't smash nubots.net
    - toolchain

# Only do branch builds on master
branches:
  only:
    - 'master'

# Setup using puppet
before_install:
  # Setup ruby so puppet works
  - rvm install ruby --latest

  # Download and install our current toolchain version
  - sudo wget -N http://nubots.net/debs/nubots-toolchain-2.1.1-travis.deb -O $TRAVIS_BUILD_DIR/toolchain/nubots-toolchain.deb
  - sudo dpkg -i $TRAVIS_BUILD_DIR/toolchain/nubots-toolchain.deb

  # Download and install the proper version of puppet
  - sudo wget -N http://apt.puppetlabs.com/puppetlabs-release-trusty.deb -O $TRAVIS_BUILD_DIR/toolchain/puppetlabs-release-trusty.deb
  - sudo dpkg -i $TRAVIS_BUILD_DIR/toolchain/puppetlabs-release-trusty.deb
  - sudo apt-get update
  - sudo apt-get install puppet

  # Install the puppet modules that are required for this install
  - sudo mkdir -p /etc/puppet/modules;
  - sudo puppet module install puppetlabs-apt --module_repository https://forge.puppet.com --version 2.4.0
  - sudo puppet module install puppetlabs-vcsrepo --module_repository https://forge.puppet.com
  - sudo puppet module install camptocamp-archive --module_repository https://forge.puppet.com
  - sudo puppet module install maestrodev-wget --module_repository https://forge.puppet.com

install:
  # Apply the puppet file to the vm
  - sudo puppet apply --parser=future --verbose --debug --modulepath=puppet/modules:/etc/puppet/modules puppet/manifests/travis.pp

  # For some reason it looks like we have to run update-alternative again on travis
  - sudo update-alternatives --remove-all gcc || true
  - sudo update-alternatives --remove-all g++ || true
  - sudo update-alternatives --remove-all gfortan || true
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-7

script:
  - export PATH=/usr/lib/ccache:$PATH
  - /usr/bin/python3 ./b platform select native
  - cd build
  - ninja
